---
- name: Set timezone to Europe/London
  community.general.timezone:
    name: "Europe/London"
  become: true
  ignore_errors: true
  
- name: Set network time use (MacOS)
  ansible.builtin.command: /usr/sbin/systemsetup -setusingnetworktime on
  changed_when: false
  become: true

- name: Set network time server (MacOS)
  ansible.builtin.command: /usr/sbin/systemsetup -setnetworktimeserver "{{ ccdc_ntp_servers[0] }}"
  changed_when: false
  become: true
