---
- name: Set timezone to Europe/London
  timezone:
    name: "Europe/London"
  become: yes

- name: Set network time use (MacOS)
  command: /usr/sbin/systemsetup -setusingnetworktime on
  changed_when: false
  become: yes

- name: Set network time server (MacOS)
  command: /usr/sbin/systemsetup -setnetworktimeserver "{{ ccdc_ntp_servers[0] }}"
  changed_when: false
  become: yes
