---
- name: Ensure timezone packages are installed.
  ansible.builtin.package:
    name: "{{ chrony_tzdata_package }}"
    state: present
  become: true

- name: Set timezone to Europe/London
  community.general.timezone:
    name: "Europe/London"
  become: true

- name: Generate chrony.conf file
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    mode: u=rw,g=r,o=r
  notify: Restart chrony service
  become: true

- name: Ensure chrony package is installed.
  ansible.builtin.package:
    name: "{{ chrony_server_package }}"
    state: present
  become: true

- name: Ensure chrony service is running
  ansible.builtin.service:
    name: "{{ chrony_daemon }}"
    state: started
    enabled: true
  become: true
