---
- name: Set timezone to Europe/London (Windows)
  win_timezone:
    timezone: GMT Standard Time

- name: Start NTP service (Windows)
  win_service:
    name: w32time
    state: started
    start_mode: auto

- name: Configure NTP (Windows)
  win_command: w32tm /config /manualpeerlist:"{{ ccdc_ntp_servers[0] }}" /reliable:yes /update
  changed_when: false
