---
- name: Restart ntp service
  ansible.builtin.service:
    name: "{{ ntp_daemon }}"
    state: restarted
  become: true
  when: ntp_daemon is defined

- name: Restart chrony service
  ansible.builtin.service:
    name: "{{ chrony_daemon }}"
    state: restarted
  become: true
  when: chrony_daemon is defined
